Boot_Seed =True
Bootstrap =True
Data_DIR =C:\Users\tuttl\OneDrive\Documents\My Documents\KlevitHahn\hdx-ms\pyHXExpress\Bimodal_HDX_Data
Data_Type =1
Env_limit =1.0
Env_threshold =0.1
Full_boot =True
Hide_Figure_Output =False
Keep_Raw =True
Limit_by_envelope =False
Max_Pops =3
Metadf_File =hdxms_testsets_metadf.csv
Nboot =20
Ncurve_p_accept =0.02
Overlay_reps =True
Pop_Thresh =0.03
process_ALL =False
setNoise =False
Random_Seed =16
Read_meta =None
SVG =False
Scale_Y_Values =True
Test_Data =True
User_mutants =['B1B6', 'HSPB1']
User_peptides =['0078-0094']
Y_ERR =1.0
WRITE_PARAMS =True
